"""Exploratory screen: which Combine measurements relate to NFL outcomes, by position group?

For every (combine feature, outcome) pair we report the Spearman correlation and
the partial Spearman correlation controlling for draft slot. The partial is the
interesting one: it asks what a measurement tells you *beyond* what teams
already priced in when they drafted the player.

Hundreds of pairs are tested on ~40-120 players per group, so treat this as a
hypothesis generator, not as findings.

    python scripts/first_look.py   # writes reports/first_look.md
"""
from __future__ import annotations

import sys
from pathlib import Path

import numpy as np
import polars as pl

sys.path.insert(0, str(Path(__file__).resolve().parents[1] / "src"))
from bdb27 import data  # noqa: E402

UNDRAFTED_PICK = 260
LAST_SEASON = 2025
MIN_N = 25
TOP_K = 8

OFFICIAL = [
    "combine_height", "combine_weight", "hand_size", "arm_length", "wing_span", "ten_yd_split",
    "forty", "vertical", "broad_jump", "three_cone", "short_shuttle", "bench_reps", "ngs_athleticism_score",
]

# (outcome column, higher_is_better) per position group
OUTCOMES = {
    "WR": [("starts_per_season", True), ("yards_per_route", True), ("mean_separation", True), ("game_top_speed", True)],
    "TE": [("starts_per_season", True), ("yards_per_route", True), ("mean_separation", True)],
    "OL": [("starts_per_season", True), ("pressure_allowed_rate", False), ("mean_peak_pressure_prob_allowed", False)],
    "DL": [("starts_per_season", True), ("pressure_rate", True), ("mean_get_off", False)],
    "DB": [("starts_per_season", True), ("game_top_speed", True), ("mean_cushion", None)],
}
MIN_VOLUME = {"yards_per_route": ("routes", 100), "mean_separation": ("targets", 20),
              "pressure_allowed_rate": ("pass_block_snaps", 150), "mean_peak_pressure_prob_allowed": ("pass_block_snaps", 150),
              "pressure_rate": ("pass_rush_snaps", 100), "mean_get_off": ("pass_rush_snaps", 100),
              "mean_cushion": ("coverage_snaps", 100), "game_top_speed": ("game_frames", 2000)}


def _rank(a: np.ndarray) -> np.ndarray:
    return np.argsort(np.argsort(a)).astype(float)


def _resid(y: np.ndarray, z: np.ndarray) -> np.ndarray:
    X = np.column_stack([np.ones_like(z), z])
    return y - X @ np.linalg.lstsq(X, y, rcond=None)[0]


def spearman_and_partial(x: np.ndarray, y: np.ndarray, z: np.ndarray) -> tuple[float, float]:
    rx, ry, rz = _rank(x), _rank(y), _rank(z)
    return float(np.corrcoef(rx, ry)[0, 1]), float(np.corrcoef(_resid(rx, rz), _resid(ry, rz))[0, 1])


def load() -> pl.DataFrame:
    P = data.PROCESSED
    return (
        pl.read_parquet(P / "player_base.parquet")
        .join(pl.read_parquet(P / "combine_tracking_wide.parquet"), on="nfl_id", how="left")
        .join(pl.read_parquet(P / "game_outcomes.parquet"), on="nfl_id", how="left")
        .join(pl.read_parquet(P / "game_movement.parquet"), on="nfl_id", how="left")
        .with_columns(
            draft_pick=pl.col("draft_overall_pick").fill_null(UNDRAFTED_PICK),
            starts_per_season=pl.col("career_games_started") / (LAST_SEASON - pl.col("draft_year") + 1),
        )
    )


def screen(df: pl.DataFrame, group: str) -> list[dict]:
    g = df.filter(pl.col("pos_group") == group)
    tracking = [c for c in g.columns if "__" in c and not c.endswith("n_attempts")]
    feats = [c for c in OFFICIAL + tracking if g[c].null_count() <= g.height - MIN_N]
    rows = []
    for outcome, better in OUTCOMES[group]:
        sub = g
        if outcome in MIN_VOLUME:
            vol, n = MIN_VOLUME[outcome]
            sub = sub.filter(pl.col(vol) >= n)
        for f in feats:
            s = sub.select(f, outcome, "draft_pick").drop_nulls().fill_nan(None).drop_nulls()
            if s.height < MIN_N:
                continue
            x, y, z = (s[c].to_numpy().astype(float) for c in (f, outcome, "draft_pick"))
            if np.std(x) == 0 or np.std(y) == 0:
                continue
            rho, prho = spearman_and_partial(x, y, z)
            rows.append(dict(group=group, outcome=outcome, better=better, feature=f, n=s.height, rho=rho, partial_rho=prho))
    return rows


def to_markdown(res: pl.DataFrame, df: pl.DataFrame) -> str:
    lines = [
        "# First look: Combine measurements vs. NFL outcomes",
        "",
        "Generated by `scripts/first_look.py`. Spearman ρ, and partial ρ controlling for draft slot "
        f"(undrafted = pick {UNDRAFTED_PICK}). Exploratory: many comparisons, small samples.",
        "",
        "## Coverage",
        "",
        "| group | players | with game tracking | with play outcomes |",
        "|---|---|---|---|",
    ]
    for grp in data.POSITION_GROUPS:
        g = df.filter(pl.col("pos_group") == grp)
        lines.append(f"| {grp} | {g.height} | {g['game_frames'].is_not_null().sum()} | {g['snaps'].is_not_null().sum()} |")
    for grp in data.POSITION_GROUPS:
        lines += ["", f"## {grp}"]
        for outcome, better in OUTCOMES[grp]:
            r = res.filter((pl.col("group") == grp) & (pl.col("outcome") == outcome))
            if r.is_empty():
                continue
            arrow = {True: "higher is better", False: "lower is better", None: "descriptive"}[better]
            lines += ["", f"**{outcome}** ({arrow}) — top {TOP_K} by |partial ρ|", "",
                      "| feature | n | ρ | partial ρ (vs draft slot) |", "|---|---|---|---|"]
            for row in r.sort(pl.col("partial_rho").abs(), descending=True).head(TOP_K).iter_rows(named=True):
                lines.append(f"| `{row['feature']}` | {row['n']} | {row['rho']:+.2f} | {row['partial_rho']:+.2f} |")
    return "\n".join(lines) + "\n"


def main() -> None:
    df = load()
    res = pl.DataFrame([r for grp in data.POSITION_GROUPS for r in screen(df, grp)])
    data.REPORTS.mkdir(exist_ok=True)
    res.write_csv(data.REPORTS / "first_look_correlations.csv")
    (data.REPORTS / "first_look.md").write_text(to_markdown(res, df))
    print(f"{res.height} feature/outcome pairs -> reports/first_look.md")


if __name__ == "__main__":
    main()
